### ISSUE TITLE
chebgui generates incorrect chebops for eigenvalue problem?

### ISSUE THREAD

**Issue by pefarrell** [chebfun/chebfun#1697] opened 2015-12-29 09:43 UTC
According to http://dx.doi.org/10.1002/cpa.3160080307, equation (1), the eigenproblem

    u" + lambda u x^{-1} = 0, u(0) = 0, u'(1) = 0,

has eigenvalues lambda_n = (sigma_n/2)^2, where sigma_n is the nth zero of the zeroth Bessel function J_0. (The boundary conditions imposed in (1) are written differently, but the eigenfunctions do indeed satisfy that Dirichlet boundary condition on the left.) Thus, I think the eigenvalues should be

    [1.4457964907366962, 7.6178155859155217, 18.721751697673795, 34.760071106614959, 55.733075904408544, 81.640838233082121, 112.48338212950888, 148.2607174139888, 188.97284869598326, 234.61977836892356, ...]

However, when I implement this in chebgui, I get

    lambda =
    
    2.4674
    22.2066
    61.6850
    120.9027
    199.8595
    298.5555

Looking at the generated chebeig.m, one part stands out:

    % Assign the equation to two chebops N and B suchthat N(u) = lambda*B(u).
    N = chebop(@(x,u) diff(u,2)+0./x, dom);
    B = chebop(@(x,u) -u, dom);

which is a different eigenproblem. (The division by x is acting on zero, not on -u.)

Have I made a mistake, or is this a bug in chebgui?

Thanks,

Patrick

**Comment by trefethen** [comment] 2015-12-29 09:57
Perhaps @nickhale or @tobydriscoll will wish to comment; my understanding is that to solve problems with coeffs like 1/x you have to multiply through by powers of x.  This gives the right numbers to 9 digits or so:
```
>> L = chebop(@(x,u) x*diff(u,2),[0,1]); L.lbc = 0; L.rbc = @(u) diff(u); eigs(L)
ans =
 -81.640838231041400
 -55.733075904658740
 -34.760071104229247
 -18.721751692877373
  -7.617815585487620
  -1.445796488589748
```
Assuming this is the case, would you say that the Chebfun documentation needs more clarity in this respect?

**Comment by nickhale** [comment] 2015-12-29 10:02
Can confirm, is a bug. Probably in the AD or string manipulation used to determine the eigenvalue problem from the string given in the GUI. Unfortunately I think @asgeirbirkis is the only one with any knowledge of how this works..

However, even setting
```
N = chebop(@(x,u) diff(u,2), dom);
B = chebop(@(x,u) -u./x, dom);
```
manually it still fails with an error
```
Error using eig
Input to EIG must not contain NaN or Inf.
Error in linop/eigs>getEigenvalues (line 352)
        [V, D] = eig(full(PA), full(PB));
```

Multiplying through by `x` seems to work
```
N = chebop(@(x,u) x.*diff(u,2), dom);
B = chebop(@(x,u) -u, dom);
```
```
D =
   1.445796489048211
   7.617815583890385
  18.721751693888912
  34.760071105996303
  55.733075903000177
  81.640838231906216
```

**Comment by pefarrell** [comment] 2015-12-29 10:08
Great, thanks for the very quick responses.

In an ideal world, I suppose chebfun could trap the fact that it's dividing by a power of x, and advise the user to multiply through by the appropriate power. This is straightforward for the user to do, though, so it's not very important.

**Comment by nickhale** [comment] 2015-12-30 08:08
I believe the division by `x` is caused by the fact that we first sample on 2nd-kind points (which, when evaluated, produce an inf), and then project to first kind points (which then produces a matrix of NaNs). If we projected from 1st-kind to 1st-kind, this wouldn't be a problem. However, since (as described above) you can simply multiply through by `x` I would say this is a low priority feature request.

The fact that CHEBGUI parses the input as 
```
% Assign the equation to two chebops N and B suchthat N(u) = lambda*B(u).
N = chebop(@(x,u) diff(u,2)+0./x, dom);
B = chebop(@(x,u) -u, dom);
```
is definitely a bug though, which should be fixed if possible.

**Closed** 2016-01-20 13:59 UTC
Labels: bug, chebgui, diffeq
