### ISSUE TITLE
chebfuneps, chebfun2eps, chebfun3eps

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#1778] opened 2016-03-01 17:11 UTC
This is a new issue that follows on from #1764.

As we discussed in a group meeting, Chebfun needs distinct tolerances `chebfuneps` (replacing current `eps`), `chebfun2eps`, and `chebfun3eps` in the preferences structure.  Users who worry about speed, say, should be able to work in 12 digits in 2D and 8 digits in 3D conveniently if they want while other users whose functions are simple enough to insist on 16 digits should be able to do that too.  The potential gains of loosening tolerance in multiple dimensions are too major for us not to make this a convenient part of Chebfun.

I don't think we can do a hacking session / pull request / code review on Chebfun3 until these features are introduced.  I presume the way to proceed is as something lean and modest, quite independent of the eventual large pull request that will be Chebfun3 itself.  I would imagine that @hashemi, @ajt60gaibb, and @aaustin141 should all have some interest in this.  To tell the truth this should really be in place for Spherefun too, which presumably will work with `chebfun2eps` -- right, @gradywright and @heatherw3521?

To remind you: whereas tolerance 1e-8 might speed up classic Chebfun by only a factor of 2 or less, in 2D it's more than that and in 3D more like a factor of 10.  Such numbers are too big to ignore.  Indeed for Chebfun three I think this may make the difference between "that's impressive" and "wow!".

The question of what the default values for `chebfun2eps` and `chebfun3eps` should be is not what I'm focussing on here, but I think we'll ned to resolve that question before releasing Spherefun or Chebfun3.

**Comment by gradywright** [comment] 2016-03-01 17:43
I would like to have this functionality (using `chebfun2eps`) in Spherefun as well.

**Comment by gradywright** [comment] 2016-03-01 17:52
Not yet @trefethen, but I will do it soon and get back to you.

**Comment by gradywright** [comment] 2016-03-01 18:28
Here are some preliminary results:
```
chebfunpref.setDefaults('eps',eps)
w = 1;
tic, f = spherefun(@(x,y,z) cos(w*pi*z.*tanh(20*x.*y))); a = toc;
chebfunpref.setDefaults('eps',1e-8)
tic, g = spherefun(@(x,y,z) cos(w*pi*z.*tanh(20*x.*y))); b = toc;
speedUp = a/b
[rank(f) rank(g)]
```
Results:
```
speedUp =
    2.5928
ans =
    25    12
```
And, with a more complicated function
```
chebfunpref.setDefaults('eps',eps)
w = 50;
tic, f = spherefun(@(x,y,z) cos(w*pi*z.*tanh(20*x.*y))); a = toc;
chebfunpref.setDefaults('eps',1e-8)
tic, g = spherefun(@(x,y,z) cos(w*pi*z.*tanh(20*x.*y))); b = toc;
speedUp = a/b
[rank(f) rank(g)]
```
Results:
```
speedUp =
    3.1494
ans =
    97    62
```
It doesn't look too impressive, yet.

**Comment by trefethen** [comment] 2016-03-01 18:31
@gradywright, can I check -- a `plotcoeffs` command would probably resolve this -- when you loosen `eps`, does that loosening apply to the resolution of the 1D chebfuns as well as the low-rank approximation?  It should, but in Chebfun2 it didn't, at least for a while, so the speedups were diminished; I'm unclear of the current status on that.

**Comment by gradywright** [comment] 2016-03-01 19:16
@trefethen Indeed the tolerance was not being passed to the resolution of the 1D chebfuns.  When I did this the improvements in the speedups are still not that impressive.  The issue is that for the two examples I gave, the resolution of the grid necessary to determine the ranks of the function are about the same resolution needed to resolve the row and column slices to machine precision, so no real speed up occurs since the lengths of the column and row slices do not need to increase.  Or, put another way, Phase II of the construction process only needs to use samples of the function from Phase I to construct the row and column chebfuns.

I will investigate this a bit more to see if there is a bug in the constructor that is not fully taking advantage of the looser tolerance.

**Comment by bhashemi** [comment] 2016-03-01 19:41
@gradywright , I guess here is how this works in `chebfun2`: 
Since #1765 by @nickhale ,  `pref.eps` is overwriten in the beginning of Phase 2 with `tol` computed in Phase 1. This _updated_ `pref` will be passed to 1D chebfun construction of `cols` and `rows`, when the object is created at the very end of construction. See Line 103 of `chebfun2/constructor` in the development branch. This might make a difference. 

Another point might be to pass something like `tol/vscale` to the `simplify` command called with `globalTol` flag.  See #1777 by @jaurentz .

**Comment by gradywright** [comment] 2016-03-02 13:55
Thanks @bhashemi, this is pretty much how I implemented it on my local branch.  Below are the results for an example more inline with @trefethen's from #1764:
```
disp('   eps     time      rank m-length n-length')
ff = @(x,y,z) tanh(10*(x+y+z-.3));
for chebeps = eps*10.^(0:2:12)
  chebfunpref.setDefaults('eps',chebeps)
  f = spherefun(ff);
  tic, f = spherefun(ff); t = toc;
  r = length(f);
  [m,n] = length(f);
  fprintf('%8.1e  %6.4f %7d %7d %8d\n', chebeps,t,r,m,n)
end
   eps     time      rank m-length n-length
 2.2e-16  9.0377     168     685      817
 2.2e-14  8.4941     142     647      785
 2.2e-12  1.8687     118     577      683
 2.2e-10  1.5163      91     469      575
 2.2e-08  1.2038      64     385      465
 2.2e-06  0.2421      42     263      377
 2.2e-04  0.0519      15     161      183
``` 
Here the results look a bit better, especially when going from 2.2e-16 to 2.2e-12.  There doesn't seem to be much gain until again dropping to 2.2e-6.  This is probably due to the size of the grids required to get the rank from phase 1 correctly not decreasing between 2.2e-16 and 2.2e-14, and then again from 2.2e-12 to 2.2e-8.

Note that I haven't pushed the code that produced these results as I just hacked it together.

**Comment by jrus** [comment] 2016-03-02 21:39
Do you know what the performance bottleneck is in these examples? Is the expensive part evaluating the original function more times? computing SVDs? Chopping coefficients? ...

**Comment by ajt60gaibb** [comment] 2016-05-06 20:15
I am going to close this issue because `chebfunNeps` has been added. The default value of `chebfun2eps` is still `eps`, though.

**Closed by ajt60gaibb** 2016-05-06 20:15 UTC
Labels: chebfun2/chebop2, constructor/eps
