### ISSUE TITLE
Singfun problem when testing orthogonality of chebpoly 

### ISSUE THREAD

**Issue by ajt60gaibb** [chebfun/chebfun#1560] opened 2015-07-14 18:42 UTC
It seems that Chebyshev polynomials `T_k(x)` are not orthogonal in Chebfun.

```
x = chebfun( 'x' );
for k = 1:1000
    v(k+1)=sum( chebpoly(k)./ sqrt(1-x.^2) ); 
end
plot(v)
```
![orthogonality](https://cloud.githubusercontent.com/assets/1814063/8681473/8bed06ee-2a35-11e5-8a43-21fd0d2c8afe.png)

I assume this is an issue in `singfun/sum`. It looks like when `n` is of the form `1+k*32` there can be trouble. Compare 

```
find(abs(v)>1)
ans =
  Columns 1 through 11
     1    33    65    97   129   193   257   289   321   353   385
  Columns 12 through 22
   417   449   481   513   545   577   609   641   673   705   737
  Columns 23 through 30
   769   801   833   865   897   929   961   993

1+(0:31)*32
ans =
  Columns 1 through 11
     1    33    65    97   129   161   193   225   257   289   321
  Columns 12 through 22
   353   385   417   449   481   513   545   577   609   641   673
  Columns 23 through 32
   705   737   769   801   833   865   897   929   961   993
```

**Comment by nickhale** [comment] 2015-07-14 20:47
I think it's an aliasing issue rather than one of orthogonality. In particular, `singfun.constructSmoothPart()` explicitly disables `sampleTest` for some reason.

**Comment by kuanxu** [comment] 2015-07-17 12:14
@nickhale is right. It's an aliasing problem as `sampleTest` is turned off deliberately in `constructSmoothPart@singfun`. In the absence of `sampleTest`, the length of `chebpoly(k)./ sqrt(1-x.^2)` is 1 for all problematic k. Apparently, an aliasing issue.

Here, `sampleTest` is disabled simply because of, again, ill-conditioning, the origin of all `singfun` woes. Of course, I don't like it to be disabled. But I don't have a better option. If `sampleTest` is enabled by changing Line 15 in @singfun/constructSmoothPart.m to 
```
pref.techPrefs.sampleTest = 1;
```
you'll see that dozens of chebtests fail or hang forever. These are all due to rounding errors significantly amplified by the ill conditioning.

Let's take the last test in tests/bndfun/test_cumsum.m as an example, which is very representative. In this test, we need to construct a singfun representation of <img src="http://www.sciweavers.org/tex2img.php?eq=%20%5Cfrac%7B1%7D%7B%5Csqrt%7B%28x%2B2%29%287-x%29%7D%7D%20&bc=White&fc=Black&im=jpg&fs=12&ff=arev&edit=0" align="center" border="0" alt=" \frac{1}{\sqrt{(x+2)(7-x)}} " width="131" height="51" /> on [-2, 7]. Here is what actually happens there, but a distilled version:
```
dom = [-2 7];
pow1 = -0.5;
pow2 = -0.5;
f = @(x) (x-dom(1)).^pow1.*(dom(2)-x).^pow2;
ezplot(f, dom)
```
Function `f` looks like this:
![f1](https://cloud.githubusercontent.com/assets/3542751/8737779/052145f4-2c1e-11e5-8cde-26d96f95dcbd.png)
In the construction of its `chebfun`, `f` is first mapped by `bndfun` to `g` which is defined on [-1, 1] and `g` looks like this on [-1, 1]:
```
map = @(x) diff(dom)*(x+1)/2+dom(1);
g = @(x) f(map(x));
ezplot(g, [-1 1])
```
![f2](https://cloud.githubusercontent.com/assets/3542751/8737800/40f5a930-2c1e-11e5-889a-7d7f6d81e328.png)
Then, exponents are exacted off from `g` by `singfun` to reveal its `smoothPart` `h`. 
```
h = @(x) g(x)./((x+1).^pow1.*(1-x).^pow2);
ezplot(h, [-1 1])
```
`h` looks like:
![f3](https://cloud.githubusercontent.com/assets/3542751/8737896/9330a6e0-2c1f-11e5-947c-ef13c2c83285.png)
The wiggly oscillations all over the place (not only near `-1` and `1`) are the evidence of large rounding error, first introduced by the linear map from [-2, 7] to [-1, 1] and further amplified by the ill-conditioning of the task of _exponent extraction_. 

Now if we try to construct a `chebtech2` for `h` with `sampleTest` on, 65000+ points are not enough:
```
chebtech2(h)
ans = 
  65537x1 chebtech2 array with properties:

      coeffs: [65537x1 double]
      hscale: 1
     ishappy: 0
    epslevel: 2.220446049250313e-16
```
However, if we deliberately disable `sampleTest`, we end up with reasonable length:
```
p = chebtech.techPref;
p.sampleTest = 0;
chebtech2(h, [], p)
ans = 
  5x1 chebtech2 array with properties:

      coeffs: [5x1 double]
      hscale: 1
     ishappy: 1
    epslevel: 2.220446049250313e-16
```
I was convinced empirically that disabling `sampleTest` makes our life much much easier and its disabling was set since the inception of `singfun`, traced back to 09/2013. Otherwise, we could have been fighting with dozens of failures in the entire system where singfun is counted on on a daily basis.

In theory, a problem like this can be reproduced in v4 too, though I didn't investigated. But the theory is there, in the note that @aaustin141 and I wrote which can be found in dropbox.

**Comment by ajt60gaibb** [comment] 2015-07-17 12:32
Thanks @kuanxu for your description about the situation. But, something needs to changed because it is getting the answer completely wrong.  

To me it sounds like a relaxed `sampleTest` is required, not the complete removal of the test. (Though, I have not been keeping up with all the issues that you have faced.) For example, why not do something this: 

```
dom = [-2 7];
f = @(x) (x-dom(1)).^-.5.*(dom(2)-x).^-.5;
map = @(x) diff(dom)*(x+1)/2+dom(1);
g = @(x) f(map(x));
h = @(x) g(x)./((x+1).^pow1.*(1-x).^pow2);

% Probably a sqrt(eps) error is made, relax tolerance:
prefs = chebfunpref(); 
prefs.techPrefs.eps = sqrt(eps); 
chebtech2(h, [], prefs)
```

**Comment by kuanxu** [comment] 2015-07-21 17:25
@ajt60gaibb Sorry for my slow action. There are basically two things we can try: A. Loosening the tolerance for the construction of `smoothPart` (i.e. relaxing techPrefs.eps). B. Relaxing the tolerance for sampleTest only. I guess you mentioned both in your comment, though you sort of tangled them up.

Theoretically, I think we should do A, rather than B. This is because all the function values sampled for the construction of `smoothPart` are adulterated to some extent. We should certainly lower our expectation for accuracy anyway. In fact, I tried this option when I was creating `singfun` and found that relaxing techPrefs.eps for the construction of `smoothPart`, however, doesn't work. Indeed, I tried this option again during the weekend and my observation is confirmed again. Even with techPrefs.eps being 1e-3, more than half of the tests failed due to various reasons. 

So I tried the second option, which I haven't thought about before (thanks!). This time things work perfect. All tests passed, as well as your code snippet for testing the orthogonality of chebpoly:
![error](https://cloud.githubusercontent.com/assets/3542751/8807369/f7bf4884-2fd3-11e5-9acd-639e5b42b1ff.png)

I have issued a pull request for this fix, which only touches a few functions and about a dozen tests. If you get time, go ahead to review it.

**Comment by ajt60gaibb** [comment] 2015-07-21 17:37
Great!  Pleased it worked.

**Comment by bhashemi** [comment] 2015-07-31 05:51
Here is how the first plot looks after the pull request #1567 is commited. 
![untitled](https://cloud.githubusercontent.com/assets/9217439/9001498/23215804-3750-11e5-802e-315bb514c516.jpg)

I am not sure whether we are happy with `v(513)` which is still `pi`.

**Comment by aaustin141** [comment] 2015-07-31 09:12
Hmm... everything's working OK for me, so this is a machine-dependent issue.  We may need to further bump the adjustment to the new `pref.sampleTestTol` in `singfun` by another factor of 10.

**Comment by kuanxu** [comment] 2015-07-31 09:42
@aaustin141 Failure here means sample test is passed, though aliasing takes place. So, I guess sampleTestEps should be tightened, instead of loosened?

**Comment by aaustin141** [comment] 2015-07-31 09:45
Yep, that's right.  The singfun adjustment to `pref.sampleTestTol` should become tighter.  Perhaps a factor of 10 as I originally suggested is too much, though.  I don't know.  Since the failure is only reproducible by @bhashemi at the moment, we should let him do the adjusting and tell us what works.

**Comment by bhashemi** [comment] 2015-08-01 16:41
To resolve this issue on my machine, I have to decrease the value of `pref.techPrefs.sampleTestEps` in `@singfun/constructSmoothPart.m` from `1e-7` to at least `1e-9`.

**Comment by aaustin141** [comment] 2015-11-24 12:53
@bhashemi:  Post-#1614, I no longer see that this is a problem.  Can you confirm and, if so, close this issue?

**Comment by bhashemi** [comment] 2015-11-30 18:19
Yes @aaustin141.  I don't see this problem anymore.

**Closed by bhashemi** 2015-11-30 18:19 UTC
Labels: bug, high-priority
